"""Add summary to casestudy & featured to notes

Revision ID: 21fda8579ea1
Revises: f88bea6ef7ac
Create Date: 2026-07-22 02:41:58.705171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fda8579ea1'
down_revision: Union[str, Sequence[str], None] = 'f88bea6ef7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_notes', sa.Column('featured', sa.Boolean(), nullable=True))
    op.add_column('case_studies', sa.Column('summary', sa.String(length=240), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_studies', 'summary')
    op.drop_column('build_notes', 'featured')
    # ### end Alembic commands ###
