"""Make file uploads optional for user creation

Revision ID: cea2308d3af9
Revises: 7ef2c74bcf35
Create Date: 2026-07-08 00:23:43.855499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea2308d3af9'
down_revision: Union[str, Sequence[str], None] = '7ef2c74bcf35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
