"""Add featured query

Revision ID: defeb756b8fd
Revises: 4c46de564e7d
Create Date: 2026-07-11 16:13:33.872272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'defeb756b8fd'
down_revision: Union[str, Sequence[str], None] = '4c46de564e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_studies', sa.Column('featured', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'featured')
    op.drop_column('case_studies', 'featured')
    # ### end Alembic commands ###
