"""Add experience to casestudy

Revision ID: f88bea6ef7ac
Revises: defeb756b8fd
Create Date: 2026-07-16 06:02:27.699932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88bea6ef7ac'
down_revision: Union[str, Sequence[str], None] = 'defeb756b8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_studies', sa.Column('industry', sa.String(length=40), nullable=False))
    op.add_column('case_studies', sa.Column('experience_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'case_studies', 'experiences', ['experience_id'], ['id'])
    op.drop_column('case_studies', 'product_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_studies', sa.Column('product_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'case_studies', type_='foreignkey')
    op.drop_column('case_studies', 'experience_id')
    op.drop_column('case_studies', 'industry')
    # ### end Alembic commands ###
